
services:
  wishlist-db:
    container_name: wishlist-db
    image: postgres:16
    environment:
      POSTGRES_DB: wishlist
      POSTGRES_USER: wishlist
      POSTGRES_PASSWORD: wishlist
    ports:
      - "5432:5432"
  
  wishlist-api:
    container_name: wishlist-api
    build: .
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      DATABASE_URL: ${APP_DOMAIN} 
      PORT: ${PORT:-8080}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - .:/app
    depends_on:
      - wishlist-db